### ISSUE TITLE
What is it for?

### ISSUE THREAD

**Issue by BarbzYHOOL** [5ury44/GoBackTester#1]
Hello,
what can it do, what is it for exactly?

Just a chart viewer?

**Comment by 5ury44** [comment]
Hello,
Thank you for checking this out! This is a back tester for trading strategies on forex. Essentially, you queue trades using the the tradeQueue attribute to trade at any millisecond in time using outside data, mean reversion, or any other strategy. This provides you infrastructure to test your strategies before implementation with a graph of your trades and profit made over time. This way, you can tell your strategy is profitable over a variety of market conditions. I can help you get started if you need any help!

Sincerely,
Suryaa

**Comment by BarbzYHOOL** [comment]
But it requires to program your strategy in python, right?

We cannot manual trade backtest with it?

**Comment by 5ury44** [comment]
Yes, your strategy has to be a program written in Go, however, I am working on a way for Python strategies to be integrated if that is something that interests you. Usually these strategies are under 50 lines and I've included an example to follow. Given that this is trading on millisecond data, I feel that it may be impractical to place trades manually- if you do feel this could be useful I can release something for that though.

**Comment by BarbzYHOOL** [comment]
No, sorry I'm too newbie to do these. I need to train manually (drawing on charts etc) before even thinking at automating a strategy
